#
# Adorade (v2.1.0): .stylelintrc.yaml
# Copyright (c) 2019-23 Adorade (https://adorade.ro)
# Licensed under MIT
# ==============================================================================
---
# extends
extends: [ '@adorade/stylelint-config' ]
