#
# Adorade (v1.0.0): .travis.yml
# Copyright (c) 2019 Adorade. All Rights Reserved.
# Licensed under MIT
#
# Travis continuous integration system configuration file.
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

language: node_js

os: linux

dist: focal

node_js:
  - "lts/*"

git:
  depth: 4

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn global add gulp-cli

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: verify
      script: yarn run verify
    - stage: build
      script: yarn run build
