# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Node CI

on:
  push:
    branches: [main, content, develop, forms, theme]
  pull_request:
    branches: [main]
  schedule:
  - cron: 0 9 * * SAT

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [22]

    runs-on: ${{ matrix.os }}

    steps:
      # checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # use node.js matrix
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      # install dependencies
      - name: Clean install dependencies
        run: yarn install

      # verify build tools
      - name: Verify build tools
        run: yarn run verify

      # build proccess
      - name: Build proccess
        run: yarn run build
